baseurl = ""
languageCode = "zh-CN"
title = "海德沙龙·翻译组"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = "headsalonfanyizu"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12

[permalinks]
    post = "/post/:year/:month/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "我们是一群搬砖工，负责将英文世界的好文章搬进中文世界"
    summary_length = 300
    github_edit = "https://github.com/headsalon/fanyizu/edit/master/content/"
    footer = "&copy; [海德沙龙](https://headsalon.org/) | [微博](https://weibo.com/headsalon) | [公众号](/about)"
    staticman_endpoint = "https://api.staticman.net/v2/entry/"
    staticman_username = "headsalon"
    staticman_repository = "fanyizu"
    staticman_branch = "master"

[params.text]
    back = "&larr; 返回首页"
    edit = "编辑本页 &rarr;"
    truncated = "&hellip;&hellip;"
    tags = "关键词："
    comment = "发表/查看评论"
    uncategorized = "未分类"
    title_categories = "栏目分类"
    title_tags = "关键词列表"
    plot_maker = "制图"
    proof_reader = "校对"
    second_proof_reader = "二校"
    translator = "翻译"
    link = "网址"
    writing_time = "写作时间"
    source = "来源"
    author = "作者"
    original_edito = "编辑"
    description = "点评"

